### ISSUE TITLE
Channels 2

### ISSUE THREAD

**Issue by AstraLuma** [django-wiki/django-nyt#97]
It looks like you're still using Channels 1.

```
Internal Server Error: /wiki/create-root/
Traceback (most recent call last):
  File "$PROJ_VENV/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "$PROJ_VENV/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "$PROJ_VENV/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "$PROJ_VENV/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/views/article.py", line 994, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "$PROJ_VENV/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "$PROJ_VENV0/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/views/article.py", line 997, in form_valid
    models.URLPath.create_root(
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/models/urlpath.py", line 247, in create_root
    article.add_revision(revision, save=True)
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/models/article.py", line 171, in add_revision
    new_revision.save()
  File "$PROJ_VENV/lib/python3.9/site-packages/django/db/models/base.py", line 748, in save
    self.save_base(using=using, force_insert=force_insert,
  File "$PROJ_VENV/lib/python3.9/site-packages/django/db/models/base.py", line 796, in save_base
    post_save.send(
  File "$PROJ_VENV/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "$PROJ_VENV/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/decorators.py", line 190, in wrapper
    return signal_handler(*args, **kwargs)
  File "$PROJ_VENV/lib/python3.9/site-packages/wiki/plugins/notifications/models.py", line 61, in post_article_revision_save
    notify(
  File "$PROJ_VENV/lib/python3.9/site-packages/django_nyt/utils.py", line 55, in notify
    from django_nyt import subscribers
  File "$PROJ_VENV/lib/python3.9/site-packages/django_nyt/subscribers.py", line 3, in <module>
    from channels import Group
ImportError: cannot import name 'Group' from 'channels' ($PROJ_VENV/lib/python3.9/site-packages/channels/__init__.py)
```

**Comment by benjaoming** [comment]
Someone already dedicated some time and work here: https://github.com/django-wiki/django-nyt/pull/85

Would you be able to have a look at that?

**Comment by AstraLuma** [comment]
Maybe, I've got a lot of different stuff going on, though.
